version: '3.8'

services:
  db:
    image: postgres:14.9
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=zxcvbnmzxc
      - POSTGRES_DB=quiz
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "alembic upgrade 7f0d38be4e69 && uvicorn app.main:app --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=quiz
      - DB_USER=postgres
      - DB_PASS=zxcvbnmzxc
    depends_on:
      - db
        
volumes:
  db_data: